export const UPDATE_QUOTE = "UPDATE_QUOTE";
export const UPDATE_ANSWERS = "UPDATE_ANSWERS";
export const GET_QUOTES_FETCH = "GET_QUOTES_FETCH";
export const GET_QUOTES_FETCH_TRIGGER = "GET_QUOTES_FETCH_TRIGGER";
export const REST_ANSWERS = "REST_ANSWERS";
